server.port=${PORT:8080}

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP ? essencial para PgBouncer/Supabase Pooler
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# Logging
logging.level.root=INFO
logging.level.com.heineken=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG