# Servidor
server.port=8080

# Supabase / PostgreSQL - Conexao Direta
spring.datasource.url=jdbc:postgresql://db.zmytikdzgyspeemwskej.supabase.co:5432/postgres
spring.datasource.username=postgres.zmytikdzgyspeemwskej
spring.datasource.password=Residencia$3484

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=heineken-secret-key-must-be-very-long-for-security
jwt.expiration-ms=86400000